#pragma once

#define ICON_STRO_TRASH_CAN u8"\ufa78"
#define ICON_STRO_PLUS u8"\uf415"
#define ICON_STRO_MINUS u8"\uf374"


#define BUTTON_LABEL_RESET ICON_STRO_TRASH_CAN
#define BUTTON_LABEL_PLUS ICON_STRO_PLUS
#define BUTTON_LABEL_MINUS ICON_STRO_MINUS
