name: Win

on:
  push:
    branches:
    - DemoApp

jobs:
  build_Win_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPLUGIN_ENABLE_LCL_BROKER=ON
    - name: build
      run: cmake --build build --config Release
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: CashMe_Windows_x64
        path: bin\CashMe_Windows_x64.exe
